import type { Metadata } from "next";
import { AuthProvider } from "./Login/AuthContext";
import "./globals.css";

export const metadata: Metadata = {
  title: "Scroll Battle",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={`antialiased`}>{children}</body>
      </AuthProvider>
    </html>
  );
}
