import type { Metadata } from "next";
import { AuthProvider } from "./Login/AuthContext";
import { MenuProvider } from "./ui/Menus/MenuContext";
import "./globals.css";

export const metadata: Metadata = {
  title: "Scroll Battle",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <MenuProvider>
        <AuthProvider>
          <body className={`antialiased`}>{children}</body>
        </AuthProvider>
      </MenuProvider>
    </html>
  );
}
